### ISSUE TITLE
Duplicate rows in k2 1arcsec match?

### ISSUE THREAD

**Issue by smoh** [megbedell/gaia-kepler.fun#1]
Probably not an issue but a question but are duplicated rows expected?
There are rows with the same EPIC number but different `k2_campaign_str`, but even taking that into account there seem to be complete duplicate rows ([snippet](https://github.com/smoh/notebook/blob/master/gaia-kepler-fun-duplicates.ipynb)).

**Comment by megbedell** [comment]
Yes, this is expected behavior in crowded regions. The cross-match goes through the [k2targets](https://exoplanetarchive.ipac.caltech.edu/cgi-bin/TblView/nph-tblView?app=ExoTbls&config=k2targets) table and returns any/all Gaia sources within 1 arcsec of the K2 target - if targets are within ~1 arcsec of each other then both may match with the same Gaia source, so it'll show up multiple times. On top of that, the k2targets table has rows for each K2 campaign, so as you note the targets observed in more than one campaign will be duplicated with different `k2_campaign_str` and their Gaia matches will show up again.

For example in your snippet, EPIC 211431574 shows up a total of four times because it was observed in two K2 campaigns and each time it matched to two Gaia sources (604941883034049280 and 664293387559886464). Similarly, because this is within a cluster (NGC 2682), Gaia source 604941883034049280 also matches to other extremely nearby EPIC objects (like EPIC 211431572), so it shows up in other rows.

I think the Kepler catalog is much better behaved in this respect because the KIC was carefully designed whereas the EPIC was crowd-sourced and done more experimentally so very crowded fields and accidental duplicates are more likely!

**Comment by smoh** [comment]
I see, thanks a lot for clearing that up!
